name: Auto Release

on:
  push:
    branches:
      - main
      - develop

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10 # or your required version

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Run tests
        run: pnpm test

      - name: Determine environment
        run: |
          if [ "${GITHUB_REF_NAME}" == "develop" ]; then
          echo "ENV=development" >> $GITHUB_ENV
          else
          echo "ENV=production" >> $GITHUB_ENV
          fi

      - name: Set up git user
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Bump version & create tag
        id: version
        run: |
          if [ "${GITHUB_REF_NAME}" == "develop" ]; then
            pnpm run release -- --prerelease alpha
          else
            pnpm run release
          fi
          echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Push changes & tags
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: 'chore(release): v${{ env.VERSION }}'
          tag: 'v${{ env.VERSION }}'
          branch: ${{ github.ref_name }}
          push_options: '--follow-tags'

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: 'v${{ env.VERSION }}'
          name: 'Release v${{ env.VERSION }}'
          body: 'Automated release from commit ${{ github.sha }} on branch ${{ github.ref_name }}'
