name: CI + Gemini AI Review

on:
  pull_request:
    branches: [main]
  issues:
    types: [opened]
  workflow_dispatch:

jobs:
  ci-and-gemini:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true

      - name: Run ESLint
        run: pnpm lint

      - name: Run Tests
        run: pnpm test || echo "Tests failed but continuing to AI review"

      - name: Run Gemini CLI
        uses: google-github-actions/run-gemini-cli@v0.1.1
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          prompt: 'Review this pull request according to our guidelines.'
          settings: |
            {
              "config_file": "GEMINI.md"
            }
