name: Gemini CLI Automation

on:
  pull_request:
    branches: [main]
  issues:
    types: [opened]
  workflow_dispatch:

jobs:
  ai-assistant:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false

      - name: Run Gemini CLI Action
        uses: google-github-actions/run-gemini-cli@v1
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          prompt: |
            You are an AI assistant. Triage and label this issue and review this pull request.
