name: Sync Commit Conventions to Wiki

on:
  push:
    paths:
      - 'docs/commit-conventions.md'

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout Wiki repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          token: ${{ secrets.GITHUB_TOKEN }}
          path: wiki

      - name: Copy file to wiki
        run: |
          cp docs/commit-conventions.md wiki/Commit-Conventions.md
          cd wiki
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add Commit-Conventions.md
          git commit -m "docs: sync commit conventions"
          git push
