name: Sync Commit Conventions to Wiki

on:
  push:
    branches:
      - main

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync docs to wiki
        env:
          PAT: ${{ secrets.GH_PAT }}
        run: |
          git clone https://$PAT@github.com/${{ github.repository }}.wiki.git wiki
          cp README.md wiki/Home.md
          cp docs/*.md wiki/ || true
          cd wiki
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Sync docs from main repo" || echo "No changes to commit"
          git push


